# SPDX-License-Identifier: Apache-2.0

name: Lint GitHub Actions workflows
on:
  push:
    branches:
      - "main"
    paths:
      - '.github/workflows/*.ya?ml'
      - '.github/workflows/actionlint.*'
  pull_request:
    branches:
      - "main"
    paths:
      - '.github/workflows/*.ya?ml'
      - '.github/workflows/actionlint.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: "Harden Runner"
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: "Checkout"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Download actionlint"
        run: |
          docker build --tag actionlint - < .github/workflows/actionlint.dockerfile

      - name: "Check workflow files"
        run: |
          echo "::add-matcher::.github/workflows/matchers/actionlint.json"
          docker run --volume="${PWD}:/repo" --workdir=/repo actionlint -color
