# SPDX-License-Identifier: Apache-2.0

name: Build AMI with Packer

on:
  workflow_dispatch:

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

jobs:
  build-ami:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for OIDC
      contents: read

    steps:
      - name: "Harden Runner"
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885
        with:
          role-to-assume: arn:aws:iam::851725220677:role/github-actions-packer-role
          aws-region: us-east-2
          role-session-name: github-actions-packer  # For tracking in CloudTrail

      - name: Setup Packer
        uses: hashicorp/setup-packer@c3d53c525d422944e50ee27b840746d6522b08de

      - name: Build and create AMI
        run: |
          set -euo pipefail
          cd scripts/packer
          packer init .
          packer validate .
          packer build .
